### ISSUE TITLE
Cant install ffmpeg 

### ISSUE THREAD

**Issue by NoNotNick** [Hackzzila/node-ffmpeg-binaries#16]
`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\rexal\Desktop\stuff\scripts> npm install ffmpeg-binaries

> lzma-native@3.0.8 install C:\Users\rexal\Desktop\stuff\scripts\node_modules\decompress-tarxz\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v67-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and node@11.2.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v67-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and node@11.2.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
WWarning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilationarning:
unrecognized setting VCCLCompilerTool/MultiProcessorCompilation

WWarning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
arning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2025, in GenerateOutput
    version=msvs_version)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 213, in __init__
    self.Write()
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 340, in Write
    f.close()
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\common.py", line 393, in close
    os.rename(self.tmp_path, filename)
WindowsError: [Error 183] Cannot create a file when that file already exists
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\rexal\\Desktop\\stuff\\scripts\\node_modules\\decompress-tarxz\\node_modules\\lzma-native\\binding-v3.0.8-node-v67-win32-x64\\lzma_native.node" "--module_name=lzma_native" "--module_path=C:\\Users\\rexal\\Desktop\\stuff\\scripts\\node_modules\\decompress-tarxz\\node_modules\\lzma-native\\binding-v3.0.8-node-v67-win32-x64"
gyp ERR! cwd C:\Users\rexal\Desktop\stuff\scripts\node_modules\decompress-tarxz\node_modules\lzma-native
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js
configure --fallback-to-build --module=C:\Users\rexal\Desktop\stuff\scripts\node_modules\decompress-tarxz\node_modules\lzma-native\binding-v3.0.8-node-v67-win32-x64\lzma_native.node --module_name=lzma_native --module_path=C:\Users\rexal\Desktop\stuff\scripts\node_modules\decompress-tarxz\node_modules\lzma-native\binding-v3.0.8-node-v67-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\rexal\Desktop\stuff\scripts\node_modules\decompress-tarxz\node_modules\lzma-native\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rexal\\Desktop\\stuff\\scripts\\node_modules\\decompress-tarxz\\node_modules\\lzma-native\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\rexal\Desktop\stuff\scripts\node_modules\decompress-tarxz\node_modules\lzma-native
node-pre-gyp ERR! node -v v11.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\rexal\Desktop\stuff\scripts\node_modules\decompress-tarxz\node_modules\lzma-native\binding-v3.0.8-node-v67-win32-x64\lzma_native.node --module_name=lzma_native --module_path=C:\Users\rexal\Desktop\stuff\scripts\node_modules\decompress-tarxz\node_modules\lzma-native\binding-v3.0.8-node-v67-win32-x64' (1)
npm WARN @angular/core@5.2.3 requires a peer of rxjs@^5.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/core@5.2.3 requires a peer of zone.js@^0.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is
installed. You must install peer dependencies yourself.
npm WARN scripts@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@3.0.8 install: `node-pre-gyp install --fallback-to-build &&
node node_modules/rimraf/bin.js build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@3.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rexal\AppData\Roaming\npm-cache\_logs\2018-11-17T18_12_19_720Z-debug.log`

**Comment by IxPrumxI** [comment]
check that https://www.npmjs.com/package/windows-build-tools

**Comment by tomo92s** [comment]
I have the same error on Debian Stretch. Any solution?

**Comment by bartbutenaers** [comment]
Hi Zach (@Hackzzila),

I have a similar issue on Raspbian Stretch (running on Raspberry Pi 3):
pi@raspberrypi-deepspeach:~/.node-red $ npm install ffmpeg-binaries

> lzma-native@3.0.8 install /home/pi/.node-red/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build
node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v64-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and node@10.14.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-node-v64-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and node@10.14.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)

Would be nice if you could have a look at it ...
P.S. I 'assume' that the **arm64** build should be downloaded, but I'm not sure ?

Thanks !
Bart

**Comment by ElCapitanHaddock** [comment]
bump, same issue

**Comment by iamfabio** [comment]
Had the same issue. After a couple hours of troubleshooting, I found a solution. The problem here is the Node version of the **Current** release, meaning Node v11.0.0 and above. Here are the steps:
1. Uninstall Node.js v11 (Current)
2. [Download Node.js v10 (LTS) from their website](https://nodejs.org/)
3. Install Node.js v10 (LTS)
4. Try executing `npm i ffmpeg-binaries` again, optionally global install `-g`

Should be working fine now. That's all I had to do.

**Comment by tomo92s** [comment]
> Had the same issue. After a couple hours of troubleshooting, I found a solution. The problem here is the Node version of the **Current** release, meaning Node v11.0.0 and above. Here are the steps:
> 
> 1. Uninstall Node.js v11 (Current)
> 2. [Download Node.js v10 (LTS) from their website](https://nodejs.org/)
> 3. Install Node.js v10 (LTS)
> 4. Try executing `npm i ffmpeg-binaries` again, optionally global install `-g`
> 
> Should be working fine now. That's all I had to do.

Not working ;/

**Comment by iamfabio** [comment]
@tomo92s I am pretty certain it is a Node version issue. Can you run `node`, then run `process.versions`? It should return an object with versions. the `modules` property needs to be on **64**. If you have **67**, it means you are most likely on Node v11. Downgrade your Node version to v10.

**Comment by tomo92s** [comment]
@JustFabiolous I have installed v10.15.0 and still cant install ffmpeg-binaries

**Comment by Sirboys** [comment]
This reason FFMPEG,FFPLAY etc. files download from 
https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.zip but this website doesn't work(( FFMPEG working only for linux
